### PR TITLE
Included Arrow source code in Malibu Adv & Story pages integrated with Arrow styles 

### PR DESCRIPTION
**Pull request by VeenaYemmiganur**
# Description
Included Arrow source code in Malibu Adv & Story pages integrated with Arrow styles 
Story templates added as Critical CSS  for SSR

#Fixes # (issue-reference)
https://github.com/quintype/ace-planning/issues/667

#Metrics
**LHCI**
https://lighthouse-ci.staging.quinpress.com/app/projects/malibu-advanced/compare/8ac9eea74a0c

**PSI**
Screenshot 2022-08-24 at 5 30 20 PM

### CODE REVIEW

**Comment by archanaknayanar** [comment]
###  QA findings - story pages
https://docs.google.com/spreadsheets/d/1HKiGfugBwHyTfskLSj6s19nLnBSHoqJUFjNWuPA8phw/edit?usp=sharing
image

**Comment by archanaknayanar** [comment]
### PSI Metrics with different arrow collection component in first row
image

**Comment by archanaknayanar** [comment]
### PSI Metrics  - feature branch vs master
image

**Review by Jeevan-Kishore — APPROVED** [review]

**Comment by archanaknayanar** [comment]
- [ ] author name and images are now not displayed for all stories
- [ ] web stories are coming in infinite scroll
- [ ] a small content jump is still there while clicking share button

**Comment by archanaknayanar** [comment]
### [After fix] PSI Metrics - feature branch (malibu-advanced) vs master(malibu-perf-advanced)


image

**Review by Jeevan-Kishore — APPROVED** [review]

**Review by nandap4790 — APPROVED** [review]

**Pull request merged**
